Add dmi2svg as a function that returns css in a string
tgstation/rust-g pull request #149
Opened 2023-08-09 02:24 UTC by tigercat2000

I'm using this to make `/datum/asset/spritesheet_svg`, see [this](https://github.com/ShadowLarkens/CHOMPStation2/commit/7917fbd23d824dad21f86af5745e0d29b40869a6#diff-9b53cb11218b0be4234bad019e2c8816727577284da071c847c01c34c2fa7b32R114) for an example of usage.

tl;dr
```dm
fcopy(icon_you_want_svgs_of, "icon.dmi");
// first argument is source file, second argument is target css
// third is an associative map of names.
// if you want to, for example, change "icon-state-a" to "statea", you would do `json_encode(list("icon-state-a" = "statea"))`
rustg_dmi_convert_to_svg("icon.dmi", "icon.css", json_encode(list()))
// If you want the actual CSS text in memory:
var/css = file2text("icon.css")
// Otherwise if you're just sending it to a client:
fcopy_rsc("icon.css")
```

Basically, this uses my new library, [`dmi2svg`](https://github.com/tigercat2000/dmi2svg), to take a dmi file and convert all of the sprites within into svg paths using the `contour_tracing` library.

Known limitations right now:
 - Animated icons are not supported
 - Directional icons have to be split into separate states if you want to render each direction.

If you provide a DMI with either of these, it just grabs the first frame facing SOUTH and discards the rest. This is already good enough for my usecase, but I'm open to supporting these if people would like them.

Cargo.lock got updated because of a conflict in `thiserror` version requirements.

2023-08-14 17:34 UTC, ZeWaka requested changes

2023-08-14 17:34 UTC, ZeWaka commented on Cargo.toml
> +dmi2svg = { git = "https://github.com/tigercat2000/dmi2svg", optional = true }
this should be [set to a release](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) using `rev` or `tag`

2023-08-14 17:34 UTC, ZeWaka commented on dmsrc/dmi.dm
> +#define rustg_dmi_convert_to_svg_symbols(fname, output, namemap) RUSTG_CALL(RUST_G, "dmi_convert_to_svg_symbols")(fname, output, namemap)
what's with the _symbols suffix?
Bit unclear what's the actual difference between the 'svg symbols' one and the 'svg css' one - why use either

2024-12-29 04:29 UTC, tigercat2000 commented
This seems unnecessary now that 516 has Edge and we can just nearest neighbor upscale stuff.

2024-12-29 04:29 UTC, closed without merging