Shutdown implementation which hooks into /world/Del
tgstation/rust-g pull request #155
Opened 2023-10-29 06:36 UTC by ZephyrTFA

Add shutdown handling for rust-g

Move log closing to said proc.
Implement job detaching for said proc.

2023-10-29 06:54 UTC, ZeWaka requested changes

2023-10-29 06:54 UTC, ZeWaka commented on dmsrc/log.dm
> -#define rustg_log_write(fname, text, format) RUSTG_CALL(RUST_G, "log_write")(fname, text, format)
no

2023-10-29 12:32 UTC, AffectedArc07 commented
Wonder if this would fix our need to have a patch on the HTTP client that has a designated create and shutdown method.

2023-10-29 19:13 UTC, ZeWaka requested changes

2023-10-29 19:13 UTC, ZeWaka commented on dmsrc/world.dm
> +	RUSTG_CALL(RUST_G, "shutdown_rustg")
This'll end up just copying itself  in the rust_g.dm file right? It needs documentation on what it's doing and why it's doing it then.
Some codebases are particular about ordering. See: you don't want this before the `logs << "shutting down"` logging entry.

2023-10-29 19:42 UTC, optimumtact commented
where do they go when they get detatched.

2023-10-29 21:50 UTC, ZephyrTFA commented
> where do they go when they get detatched.

No where, we just drop our reference to them which means that they become free standing threads. There's no easy way to hook cancelation logic in and leaving them orphaned won't cause any problems

2023-10-30 15:07 UTC, willox commented
"Detaching" the threads would mean they may still exist after the module is unloaded which will result in a crash. It doesn't do anything.

2023-11-02 08:22 UTC, closed without merging