add random_replacetext, a replacement for stars()
tgstation/rust-g pull request #168
Opened 2024-04-15 08:33 UTC by Kapu1178

Adds a new function, `random_replacetext()`, which randomly replaces non-whitespace characters in a string with another character. This is to replace the `stars()` function found in every SS13 codebase, which is awfully, awfully slow due to byond's string interning.

Please ignore the overtime values for this, as I simply ran each proc 10,000 times in the same tick.
![image](https://github.com/tgstation/rust-g/assets/75460809/6ff70f7f-026e-47bf-8df6-7e88928f34c6)

2024-04-15 08:34 UTC, Kapu1178 commented on dmsrc/random_replacetext.dm
> +#define rustg_random_replacetext(text, probability, replacement) RUSTG_CALL(RUST_G, "random_replacetext")(text, probability, replacement)
```suggestion
#define rustg_random_replacetext(text, probability, replacement) RUSTG_CALL(RUST_G, "random_replacetext")(text, "[probability]", replacement)
```

2024-04-15 19:28 UTC, ZeWaka reviewed
i don't think this is worth the compile time of 2 seconds max, much less the maintainer overhead and me having to write this sentence

2024-04-15 19:31 UTC, Kapu1178 commented
> i don't think this is worth the compile time of 2 seconds max, much less the maintainer overhead and me having to write this sentence

So, let's put into perspective why this is useful. This proc, on TG, is labelled as so expensive you should never use it. It used to be a crash vector on Paradise. This proc used to be used alot, but was scrubbed away because of the cost it incurred. Besides, this code is braindead simple (because im braindead and I wrote it), maintaining it isn't exactly a challenge.

2024-04-16 03:07 UTC, ZeWaka requested changes
blocking: feature not documented properly in code nor in readme

if you can get another maintainer not from daedalus to care about this we can merge it

2024-04-16 03:07 UTC, ZeWaka commented on src/random_replacetext.rs
> +    let prob = prob_as_str.parse::<u32>()?;
Have you considered how this error will propagate up?

2024-04-21 01:52 UTC, closed without merging