Remove error when compiling for 64bit
tgstation/rust-g pull request #182
Opened 2024-07-15 10:44 UTC by MrStonedOne

This is required for OD support and this has turned error that was suppose to prevent footguns into an error that is itself a footgun.

2024-07-15 15:58 UTC, ZeWaka commented
While this is good/necessary, we should probably bold / emphasize the bit in the readme even more so less people fall for the issue.

I don't see an easy way to emit compiler info statements unfortunately. See, this issue which is maybe familiar: https://internals.rust-lang.org/t/pre-rfc-add-compile-warning-macro/9370/8 and  https://github.com/rust-lang/rust/issues/54140

2024-07-15 23:34 UTC, Cyberboss commented
Is it possible to feature flag gate the error?

2024-07-16 05:20 UTC, ZeWaka commented
> Is it possible to feature flag gate the error?

```toml
[features]
allow_non_32bit = []
```
```rs
#[cfg(all(not(target_pointer_width = "32"), not(feature = "allow_non_32bit")))]
compile_error!("Compiling for non-32bit is not allowed without enabling the `allow_non_32bit` feature.");
```

2024-07-17 01:56 UTC, Cyberboss requested changes
What waka said

2024-07-20 20:12 UTC, MrStonedOne commented
Added features that block compiling under 64 bit or a rustc version that is too new for windows 7 and 8 (note, the game servers are still windows server 2012, so rustc dropping windows 8 support under 1.76 will also fuck us.

2024-08-09 06:44 UTC, MrStonedOne commented
This will be easier to copy and paste the windows 7 bits into a new webedit then to deal with conflicts, half of which are for lines that will no longer be changed.

2024-08-09 06:44 UTC, closed without merging