Turns out there is no jobs feature
tgstation/rust-g pull request #54
Opened 2020-10-26 20:56 UTC by vuonojenmustaturska

I wonder if feature-interdependencies are possible...

2020-10-26 20:57 UTC, Cyberboss approved these changes

2020-10-26 22:48 UTC, vuonojenmustaturska commented
oh yeah this is tested to compile with default features and `--features="dmi git log json noise" --no-default-features`, `jobs` is not directly a default feature but a dependency of default features `http` and `sql`

2020-10-27 00:13 UTC, Cyberboss approved these changes

2020-10-27 00:46 UTC, Cyberboss requested changes

2020-10-27 00:46 UTC, Cyberboss commented on Cargo.toml
> +flume = {version = "0.9", optional = true }
```suggestion
flume = { version = "0.9", optional = true }
```
_eye twitch_

2020-10-27 14:20 UTC, Cyberboss approved these changes

2020-10-27 20:43 UTC, merged

2020-10-27 21:09 UTC, SpaceManiac commented
hmm today I will click "Rebase Merge"

2020-10-27 21:24 UTC, Cyberboss commented
Why is it the default then?

2020-10-27 21:37 UTC, SpaceManiac commented
it remembers what you used last