Ports the UDP Client from Aurora RusT-G
tgstation/rust-g pull request #61
Opened 2021-02-08 16:10 UTC by Iamgoofball

Ports https://github.com/Aurorastation/rust-g/pull/5/

2021-02-08 20:15 UTC, Cyberboss commented
What for?

2021-02-08 20:47 UTC, optimumtact commented
your haptic feedback plugin is never going to get merged to tg mainline because we're not in the business of adding features only 1 person can use.

I don't see a problem with adding this to rust-g itself though, although it doesn't seem very useful

2021-02-08 21:28 UTC, ZeWaka requested changes
no entry in dmsrc as well

2021-02-08 21:28 UTC, ZeWaka commented on Cargo.toml
> +default = ["cellularnoise", "dmi", "file", "git", "http", "json", "log", "noise", "sql", "udp_shipper"]
lmao no

2021-02-08 21:28 UTC, ZeWaka commented on src/lib.rs
> +pub mod udp_shipper;
```suggestion
pub mod udp_shipper;

```

2021-12-15 17:33 UTC, AffectedArc07 commented
Feeling like closing this given it hasn't been touched in over 10 months,

2021-12-15 19:51 UTC, closed without merging

2021-12-15 19:51 UTC, Iamgoofball commented
i forgot it was still open myself