Add functions for seeking lines and getting line counts in functions
tgstation/rust-g pull request #95
Opened 2022-04-25 08:41 UTC by Mothblocks

Adds `rustg_file_get_line_count` for getting the line count of a given filename, and `rustg_file_seek_line` for getting a specific line.

These are useful as to not load the entire file into memory in DM, which is useful for very large files like dictionaries.

2022-04-25 12:36 UTC, AffectedArc07 requested changes
`build.rs` L 31:
```rs
let feature = uprfeature.to_lowercase().replace("_", "-"); // actual proper name of the enabled feature
```
to
```rs
let feature = uprfeature.to_lowercase().replace('_', '-'); // actual proper name of the enabled feature
```

2022-04-26 01:54 UTC, Mothblocks commented
clippy moment

2022-04-26 01:54 UTC, Mothblocks commented
i'll do it later :)

2022-04-26 10:28 UTC, AffectedArc07 commented
@Mothblocks  Also, on the topic of this
`These are useful as to not load the entire file into memory in DM, which is useful for very large files like dictionaries.`

Most dictionaries are JSON, so you would have to account for reformatting it to be readable, as well as keeping the lines in code sane to make sure it grabs the right part of the dictionary. 

This seems like more of a hassle than its worth, to be truly honest.

2022-04-26 21:05 UTC, Mothblocks commented
There are two use cases that this is made for:

1. @AnturK wanted to have the wordle dictionary, which is just a text file of words.
2. I'm using this for something where, instead of a JSON of arrays, it's just a text file where each thing is a JSON.

Both these dictionaries can be pretty sizable, and BYOND's memory limits without LAA are really small, especially when you remember rust-g's binary size contributes to it.

2022-04-26 22:29 UTC, merged